<a href="https://colab.research.google.com/github/luiztoledosilva/java_script_livro_estudo_PI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
v=np.array([1,2,3,4])
print(v)


[1 2 3 4]


In [5]:
import numpy as np
A = np.arange(15).reshape(3,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
subA = A[0:2, 2:4]
print(subA)

[[2 3]
 [7 8]]


In [7]:
u = np.array([2.0, 3.5, 4.0, -10.1])
v = u[[2,3]]
print(v)

[  4.  -10.1]


In [8]:
A = np.arange(10).reshape(2,5)
B = A[:, [2,4]]
print("A =\n", A)
print("B =\n", B)

A =
 [[0 1 2 3 4]
 [5 6 7 8 9]]
B =
 [[2 4]
 [7 9]]


In [9]:
v = np.array([10,20,30])
u = np.array([2,2,2])
w = u+v
print(w)

[12 22 32]


In [10]:
w = u*v
print("w =", w)
x = u/v
print("x =", x)

w = [20 40 60]
x = [0.2        0.1        0.06666667]


In [11]:
x = np.array([10, 20])
y = x**2
print(y)

[100 400]


In [12]:
x = np.arange(10)
media = x.mean()
menor_valor = np.min(x)
arg_max = np.argmax(x)
print("Média =", media)
print("Menor valor =", menor_valor)
print("Arg max =", arg_max)

Média = 4.5
Menor valor = 0
Arg max = 9


In [13]:
A = np.array([10, 30, 40, 20]).reshape(2,2)
menor= A.min()
menor_colunas = A.min(axis=0)
print("A = \n", A)
print("Menor valor = ", menor)
print("Menor valor em cada coluna =", menor_colunas)

A = 
 [[10 30]
 [40 20]]
Menor valor =  10
Menor valor em cada coluna = [10 20]


In [14]:
w = np.dot(u, v)
print("w =", w)
x = u.dot(v)
print("x =", x)

w = 120
x = 120


In [15]:
print("w =", w)
x = 10*w
print("x =", x)

w = 120
x = 1200


In [17]:
def produto_interno(u, v):
  prod = 0
  for i in range(u.size):
    prod+=u[i]*v[i]
    return prod
u = np.random.rand(10000)
v = np.random.rand(10000)
%timeit produto_interno(u,v)
%timeit np.dot(u,v)

The slowest run took 25.56 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 957 ns per loop
The slowest run took 14.17 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 4.11 µs per loop


In [18]:
A = np.array([[10, 20], [30, 40]])
print(A)

[[10 20]
 [30 40]]


In [19]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
##continuacao livro pagina 8

In [2]:
A = np.arange(15).reshape(3,5)
print(A)

NameError: ignored

In [3]:
print(A)

NameError: ignored

In [4]:
A = np.arange(15).reshape(3,5)
print(A)

NameError: ignored

In [ ]:
print(v.dtype)

int64


In [ ]:
v = np.array([1,2,3,4], dtype='float64')
print(v.dtype)

float64


In [ ]:
v = np.array([1.0,2.0,3.0,4.0])
print(v.dtype)

float64


In [ ]:
print(v.shape)


(4,)


In [ ]:
v = np.array([1,2,3,4])
v.shape = (2,2)
print(v)

[[1 2]
 [3 4]]


In [ ]:
##função reshape

v = np.array([1,2,3,4]).reshape(2,2)
print(v)

[[1 2]
 [3 4]]


In [ ]:
v = np.array([1,2,3,4,5,6,7,8])
v = v.reshape(2, -1)
print(v)


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
v = np.array(range(50)).reshape(2,5,5)
print('Shape = ', v.shape)
print('Número de dimensões = ', v.ndim)
print('Número de elementos = ', v.size)
print('Tensor v = \n', v)

Shape =  (2, 5, 5)
Número de dimensões =  3
Número de elementos =  50
Tensor v = 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [ ]:
v = np.array(range(50)).reshape(2,5,5)
print('Shape = ', v.shape)
print('Número de dimensões = ', v.ndim)
print('Número de elementos = ', v.size)
print('Tensor v = \n', v)

Shape =  (2, 5, 5)
Número de dimensões =  3
Número de elementos =  50
Tensor v = 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [ ]:
v = np.arange(0, 5, 0.5)
u = np.linspace(0, 5, 10)
print("v =", v)
print("u =", u)

v = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
u = [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
v = np.array(range(50)).reshape(2,5,5)
print(v.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [ ]:
v_iter = v.flat
for i in v_iter:
  print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

In [ ]:
print(v[1])

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [ ]:
v = np.array([10, 20, 30, 40]).reshape(2,2)
print(v[0,1])

20


In [ ]:
v = np.arange(8).reshape(2,2,2)
print("v =\n", v)
print("\n v[0,0,1] =", v[0,0,1])

v =
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

 v[0,0,1] = 1


In [ ]:
v = np.arange(10)
u = v[1:3]
print(u)

[1 2]


In [ ]:
###pagina 5 livro