<a href="https://colab.research.google.com/github/luiztoledosilva/java_script_livro_estudo_PI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
v=np.array([1,2,3,4])
print(v)


[1 2 3 4]


In [4]:
print(v.dtype)

int64


In [5]:
v = np.array([1,2,3,4], dtype='float64')
print(v.dtype)

float64


In [6]:
v = np.array([1.0,2.0,3.0,4.0])
print(v.dtype)

float64


In [7]:
print(v.shape)


(4,)


In [9]:
v = np.array([1,2,3,4])
v.shape = (2,2)
print(v)

[[1 2]
 [3 4]]


In [10]:
##função reshape

v = np.array([1,2,3,4]).reshape(2,2)
print(v)

[[1 2]
 [3 4]]


In [11]:
v = np.array([1,2,3,4,5,6,7,8])
v = v.reshape(2, -1)
print(v)


[[1 2 3 4]
 [5 6 7 8]]


In [12]:
v = np.array(range(50)).reshape(2,5,5)
print('Shape = ', v.shape)
print('Número de dimensões = ', v.ndim)
print('Número de elementos = ', v.size)
print('Tensor v = \n', v)

Shape =  (2, 5, 5)
Número de dimensões =  3
Número de elementos =  50
Tensor v = 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [13]:
v = np.array(range(50)).reshape(2,5,5)
print('Shape = ', v.shape)
print('Número de dimensões = ', v.ndim)
print('Número de elementos = ', v.size)
print('Tensor v = \n', v)

Shape =  (2, 5, 5)
Número de dimensões =  3
Número de elementos =  50
Tensor v = 
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


In [14]:
v = np.arange(0, 5, 0.5)
u = np.linspace(0, 5, 10)
print("v =", v)
print("u =", u)

v = [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
u = [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [15]:
v = np.array(range(50)).reshape(2,5,5)
print(v.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [16]:
v_iter = v.flat
for i in v_iter:
  print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

In [17]:
print(v[1])

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [18]:
v = np.array([10, 20, 30, 40]).reshape(2,2)
print(v[0,1])

20


In [19]:
v = np.arange(8).reshape(2,2,2)
print("v =\n", v)
print("\n v[0,0,1] =", v[0,0,1])

v =
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

 v[0,0,1] = 1
